feature : add style header and banner
kienbx1/training1511 pull request #18
Opened 2022-11-22 03:12 UTC by longbachviet

2022-11-22 04:17 UTC, kienbx1 commented on src/index.html
> +  <div></div>
thừa div

2022-11-22 04:17 UTC, kienbx1 commented on src/index.html
> +      <section class="banner-container">
tab chưa hợp lý

2022-11-22 04:17 UTC, kienbx1 commented on src/index.html
> +      src="..//..//images/Rectangle296.png"
../../images/Rectangle296.png

2022-11-22 04:17 UTC, kienbx1 commented on src/index.html
> +      alt=""
thêm nội dung cho alt

2022-11-22 04:17 UTC, kienbx1 commented on src/index.html
> +  <div></div>
xóa div thừa

2022-11-22 04:17 UTC, kienbx1 commented on src/index.html
> +      src="..//..//images/Rectangle296.png"
../../images/Rectangle296.png

2022-11-22 04:17 UTC, kienbx1 commented on src/views/partials/banner.html
> +      src="..//..//images/Rectangle296.png"
..//..//images/Rectangle296.png => ../../images/Rectangle296.png

2022-11-22 04:17 UTC, kienbx1 commented on src/styles/layout/_header.scss
> +    // color: white;
xóa comment

2022-11-22 04:17 UTC, kienbx1 commented on src/styles/layout/_banner.scss
> +    max-width: 100% !important;
hạn chế dùng important

2022-11-22 04:22 UTC, diennn-gg commented on src/styles/layout/_banner.scss
> +    .banner-rectangel296 {
sao lại đặt tên class như này em

2022-11-23 01:51 UTC, BaoTranid reviewed
Kiểm tra lại các thuộc tính width, height, padding, margin, top ...

2022-11-23 01:56 UTC, BaoTranid requested changes

2022-11-23 01:56 UTC, BaoTranid commented on src/styles/layout/_header.scss
> +    .header-list__item {
scss có thể viết như thế này
```
    &__item {
      margin: 18px;
      color: white;
      cursor: pointer;
      &:hover {
          color: #5cbbe5;
       }
    }
```

2022-11-25 01:34 UTC, BaoTranid approved these changes

2022-11-25 01:37 UTC, merged