Feature/body services
kienbx1/training1511 pull request #28
Opened 2022-11-24 08:38 UTC by longbachviet

2022-11-25 04:17 UTC, BaoTranid requested changes

2022-11-25 04:17 UTC, BaoTranid commented on src/styles/layout/_banner.scss
>      left: 0px;
0px => 0

2022-11-25 04:17 UTC, BaoTranid commented on src/styles/layout/_body.scss
> -    box-shadow: 0px 2px 24px rgba(0, 0, 0, 0.08);
0px => 0

2022-11-25 04:17 UTC, BaoTranid commented on src/styles/layout/_body.scss
> +      content: " ";
" " => ""

2022-11-25 04:17 UTC, BaoTranid commented on src/styles/layout/_body.scss
> +      margin-top: 0%;
0

2022-11-28 09:17 UTC, kienbx1 approved these changes

2022-11-28 09:19 UTC, BaoTranid approved these changes

2022-11-28 09:20 UTC, merged